### PR TITLE
pl locale (język polski)

### PR DESCRIPTION
**Pull request by araczkowski**
I've added support for the Polish language.
The change was tested on my local environment - should be OK.

### CODE REVIEW

**Comment by tkem** [comment]
Awesome! You can also add yourself to `about.html` if you like - use a nick name or your real name, it's up to you ;-)

**Comment by tkem** [comment]
One question: "About" is really "About" in Polish?

**Comment by tkem** [comment]
Also `www/index.html` seems to be missing
```
    <script src="app/locale/pl.js"></script>
```

**Comment by araczkowski** [comment]
I'm in about.html :+1:
the "About" in Polish should be "O aplikacji" (probably ;) - fixed
www/index.html - fixed

Thanks for the remarks.

PS
Thank you for this application! - is very useful.

**Comment by tkem** [comment]
Merged for v1.8.2, Beta for Android should be available from Google Play store soon.
Did a little redesign of the "About" page, hope you don't mind...
Thanks for contributing!

**Comment by araczkowski** [comment]
Of course the final version it is up to you - I forgot to mention that this
was only a proposition.

Thanks man!

**Pull request merged**
